### ISSUE TITLE
Feature Change Attack Sprites

### ISSUE THREAD

**Issue by FatalXFury** [cfogrady/DIM-Modifier#10]
Hey there. Im finally using your Dim Modifier and it's awesome. It's very simple to use and like that you can have the option for the software to detect whether the bin has safe values or not. I was wondering. Is there a way to edit attack sprites somehow?

**Comment by cfogrady** [comment]
You can change which attack sprite is used. I tried to describe them as best I could for the drop down selector, but if you mean edit the art of the attack sprite or use a new attack sprite, the answer is no. This is because those sprites are stored on the device itself, not the DIM. The DIM only has an id which the device matches to a sprite stored on the device. Since my device only edits DIM image data, it simply doesn't have access to those sprite images.

**Comment by cfogrady** [comment]
Note: This is possible with new BE Memories. So I'm re-opening this feature request because I'll implement it for BE Memories. Older DIMs will still be limited to only what is available in the OS though.

**Comment by cfogrady** [comment]
Working for BE Memories as part of 2.0
