### ISSUE TITLE
Exporting Sprites

### ISSUE THREAD

**Issue by Enoque08** [cfogrady/DIM-Modifier#14]
I'd like to start saying that this program is awesome and I was really happy once I found it - Althought it took some time 😢 

It's really hard to find the Sprites other than the main sprites online. Is it possible to add a feature to export the current sprite active? As a .png so it'd make it easier to edit and visualize them. Apologies if it existis I'm just not finding, but I've been trying for a while now.

**Comment by ChaonicTheDeathKitten** [comment]
I agree. This would be amazing to have, because it would not only enable us to make edits, it'd also extremely handy as a baseline for making our own sprites. Finding information is not as easy as it should be. And this tool could be the single best resource for modders, if a batch export of sprites would be possible, even if it's on a single digimon basis.

All my wishes would come true if these exported sprites would also be named accordingly to what they are used for.

**Comment by Desbrina** [comment]
Take a look at the sprite injector tool. It exports all sprite, including name sprite

**Comment by SwayStation** [comment]
> Take a look at the sprite injector tool. It exports all sprite, including name sprite

Would you be able to share a link of where I can find this tool please?  I've been looking all over for it but so far have only been able to find mentions of it in forums and postings. Googling it doesn't bring up any download links at all.

**Comment by FatalXFury** [comment]
> 

I have it. Unfortunately, i have windows 7. It's compatible with windows 10 i believe.

**Comment by GuilTamer** [comment]
> > 
> 
> I have it. Unfortunately, i have windows 7. It's compatible with windows 10 i believe.

Could you share it?

**Comment by cfogrady** [comment]
Done as part of 2.0
