### ISSUE TITLE
home screen sprite problem for custom dim digimon vital bracelet digivice v

### ISSUE THREAD

**Issue by n11ku** [cfogrady/DIM-Modifier#5]
hello bro, the sprite in front number 1 & 2 for home screen in vbv need special green background?, like the sprite have green background,but when gonna see the sprite, the green background become transparent background?, this green background become wall to hide another sprite?,then i need sprite green background format bmp?

**Comment by n11ku** [comment]
like my magnamon bp sprite recolor by viofitz,become alot bug in home screen,alot sprite from behind is become visible like have 2 leg or 2 hand,this magnamon bp sprite is from ancient warriors dim card

**Comment by cfogrady** [comment]
Green is considered the transparent color key by the VBDM/VBV devices themselves. The best you can do is a slightly off-green. My app mirrors that, so if you are using 0,255,0 or something close to that (the device is 16-bit color instead of 32-bit), that will be transparent in my app and on the device. If you have green in your Mangamon recolor it will become transparent. Because this is a hardware limitation of the devices themselves, my best recommendation is to use a slightly different shade of green.

**Comment by n11ku** [comment]
oh ok,thank you bro
